module.exports = {
    TEAM_FETCH_API_BASE: "https://api.cesiumlabs.xyz/api/d/staffs",
    NAV: [
        { label: "Home", path: "/", external: false },
        { label: "Team", path: "/team", external: false },
        { label: "Projects", path: "/projects", external: false },
        { label: "API", path: "https://api.cesiumlabs.xyz", external: true },
        { label: "Documentation", path: "https://docs.cesiumlabs.xyz", external: false },
        {
            label: "Discord",
            path: "https://discord.gg/uqB8kxh",
            external: true,
        },
        {
            label: "GitHub",
            path: "https://github.com/CesiumLabs",
            external: true,
        },
        {
            label: "Bot Hosting",
            path: "https://bluefoxhost.com",
            external: true,
        },
    ],
    LINKS: {
        DISCORD: "https://discord.gg/uqB8kxh",
        GITHUB: "https://github.com/CesiumLabs",
    },
    PROJECTS: [
        {
            name: "Canvacord",
            github: "CesiumLabs/Canvacord",
            npm: "canvacord",
            docs: "https://canvacord.js.org",
            description: "Image manipulation tool for beginners.",
        },
        {
            name: "QuickMongo",
            github: "CesiumLabs/QuickMongo",
            npm: "quickmongo",
            docs: "https://quickmongo.js.org",
            description: "Quick mongodb wrapper for beginners.",
        },
        {
            name: "SoundCloud Scraper",
            github: "CesiumLabs/SoundCloud-Scraper",
            npm: "canvacord",
            docs: "https://soundcloud-scraper.js.org",
            description: "Fetch data from SoundCloud easily!",
        },
        {
            name: "YouTube Search",
            github: "CesiumLabs/youtube-sr",
            npm: "youtube-sr",
            docs: "https://github.com/CesiumLabs/youtube-sr",
            description: "Simple package to make youtube search.",
        },
        {
            name: "Yukitoki",
            github: "CesiumLabs/yukitoki",
            docs: "https://docs.cesiumlabs.xyz",
            description: "Customizable documentation rendering website written in Svelte.",
        },
        {
            name: "Discord YTDL Core",
            github: "CesiumLabs/discord-ytdl-core",
            npm: "discord-ytdl-core",
            docs: "https://github.com/CesiumLabs/discord-ytdl-core",
            description: "Simple ytdl wrapper for discord bots with custom ffmpeg args support.",
        },
        {
            name: "Web Screenshot",
            github: "CesiumLabs/websshot",
            npm: "websshot",
            docs: "https://github.com/CesiumLabs/websshot",
            description: "Simple package to take screenshot of given html or markdown code.",
        },
        {
            name: "Hackable Quick.db",
            github: "CesiumLabs/quick.db",
            npm: "@CesiumLabs/quick.db",
            docs: "https://github.com/CesiumLabs/quick.db",
            description: "Superset of quick.db that you can hack into.",
        },
        {
            name: "Quick Economy",
            github: "CesiumLabs/quick.eco",
            npm: "quick.eco",
            docs: "https://eco.js.org",
            description: "Simple and powerful economy framework for Discord bots.",
        },
        {
            name: "Lowdash",
            github: "CesiumLabs/lowdash",
            docs: "https://github.com/CesiumLabs/lowdash",
            description: "A Python implementation of JavaScript Lodash library.",
        },
        {
            name:"Code Examples",
            github: "CesiumLabs/code-examples",
            docs: "https://codes.cesiumlabs.xyz",
            description:"Short code snippets written by our open source community!",
        },
        {
            name: "Frost",
            github: "CesiumLabs/frost",
            docs: "https://frost.js.org",
            description: "🚀 Static site generator",
        },
    ],
    YOUTUBE_CHANNEL_ID: "UCaxSqb45cc6Ero_RkMEId1Q",
    LOGIN_URL: `https://discord.com/api/oauth2/authorize?client_id=652874564098850826&redirect_uri=https%3A%2F%2Fcesiumlabs.xyz%2Flogin&response_type=code&scope=identify`,
    LOGIN_API: "https://backend.snowflakedev.cf/api/authorize",
};
