[build]
  command = "npm run build"
  publish = "/opt/build/repo/out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200