[build]
  command = "npm run build && npm run export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/uqB8kxh"
  force = true
  status = 200

[[redirects]]
  from = "/login"
  to = "/api/auth/signin"
  force = true
  status = 200

[[redirects]]
  from = "/logout"
  to = "/api/auth/signout"
  force = true
  status = 200

[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200